matrix:
  include:
    - language: java
      jdk: openjdk8
      install: true
      # build specific modules and only log errors
      script: ./mvnw clean install -q -pl pantheon-bundle,pantheon-karaf-feature,pantheon-karaf-dist 
      after_success:
      # Move the code coverage results to codecov
      - bash <(curl -s https://codecov.io/bash) -cF java
      - bash <(curl -s https://codecov.io/bash) -cF javascript
      cache:
        directories:
        - $HOME/.m2

    - language: go
      sudo: false
      before_script:
        - cd tools/git2pantheon
      before_install:
        - go get gopkg.in/src-d/go-git.v4
      script:
        - go build
        - go test -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
      # Move the code coverage results to codecov
      - bash <(curl -s https://codecov.io/bash) -cF go