matrix:
  include:
    - language: java
      jdk: openjdk8

      cache:
        directories:
          - $HOME/.m2

      install:
        - curl -o $HOME/.m2/settings.xml     https://raw.githubusercontent.com/aprajshekhar/maven-settings/master/settings.xml
      # build specific modules and only log errors
      script: ./mvnw clean  install -q  -e -pl sling-org-apache-sling-karaf-distribution,pantheon-bundle,pantheon-karaf-feature,pantheon-karaf-dist
      after_success:
      # Move the code coverage results to codecov
      - bash <(curl -s https://codecov.io/bash) -cF java
      - bash <(curl -s https://codecov.io/bash) -cF javascript

    - language: go
      sudo: false
      before_script:
        - cd tools/git2pantheon
      before_install:
        - go get gopkg.in/src-d/go-git.v4
      script:
        - go build
        - go test -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
      # Move the code coverage results to codecov
      - bash <(curl -s https://codecov.io/bash) -cF go